# Generated by Django 4.1.6 on 2023-02-09 09:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_produits_categorie_prod_produits_etat_prod_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='post_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Store.produits'),
        ),
    ]
