# Generated by Django 4.1.6 on 2023-02-09 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_rename_post_id_photo_produit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produits',
            name='categorie_prod',
            field=models.CharField(choices=[('Appareils electro-menager', 'Appareils electro-menager'), ('Accessoires', 'Accessoires'), ('Telephone portable', 'Telephone portable'), ('Auto-mobile', 'Auto-mobile'), ('Autres', 'Autres')], default='', max_length=50, verbose_name='Catégorie'),
        ),
        migrations.AlterField(
            model_name='produits',
            name='ville_prod',
            field=models.CharField(choices=[('Bafoussam', 'Bafoussam'), ('Bamenda', 'Bamenda'), ('Bertoua', 'Bertoua'), ('Buea', 'Buea'), ('Douala', 'Douala'), ('Ebolowa', 'Ebolowa'), ('Garoua', 'Garoua'), ('Maroua', 'Maroua'), ('Ngaoundere', 'Ngaoundere'), ('Yaounde', 'Yaounde'), ('Autres', 'Autres')], default='Autres', max_length=15, verbose_name='Ville'),
        ),
    ]
