# Generated by Django 4.1.6 on 2023-02-09 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_alter_photo_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.FileField(upload_to='images/%Y/%m/%d/'),
        ),
    ]
