# Generated by Django 4.1.6 on 2023-02-09 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0007_alter_photo_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='image',
            new_name='Fichier_images',
        ),
    ]
