# Generated by Django 4.1.6 on 2023-02-11 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0008_rename_image_photo_fichier_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='Fichier_images',
        ),
        migrations.AddField(
            model_name='photo',
            name='image',
            field=models.ImageField(blank=True, upload_to='Image_Produit'),
        ),
    ]
