# Generated by Django 4.1.6 on 2023-02-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0010_produits_vendu'),
    ]

    operations = [
        migrations.AddField(
            model_name='produits',
            name='prix_promo',
            field=models.PositiveIntegerField(default=0, verbose_name='Prix promotionnel'),
        ),
    ]
