# Generated by Django 4.1.6 on 2023-02-12 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0005_alter_user_datenaiss_alter_user_photo_profil_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='DateNaiss',
            field=models.DateField(null=True, verbose_name='Date de naissance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Photo_Profil',
            field=models.ImageField(null=True, upload_to='Photo_profil', verbose_name='Photo de profil'),
        ),
        migrations.AlterField(
            model_name='user',
            name='Sexe',
            field=models.CharField(choices=[('Masculin', 'Masculin'), ('Feminin', 'Feminin')], max_length=10, null=True, verbose_name='Sexe'),
        ),
    ]
