# Generated by Django 4.1.6 on 2023-03-18 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0006_alter_user_datenaiss_alter_user_photo_profil_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Date_created',
            field=models.DateField(auto_now=True, verbose_name='Date creation compte'),
        ),
        migrations.AddField(
            model_name='user',
            name='Ville',
            field=models.CharField(blank=True, max_length=30, verbose_name='Ville'),
        ),
    ]
