# Generated by Django 4.1.6 on 2023-03-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Authentification', '0007_user_date_created_user_ville'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Prenom'),
        ),
    ]
