# Generated by Django 4.1.6 on 2023-03-05 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='photoMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to='Image_Chat')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Discussion.chatmessages')),
            ],
        ),
    ]
