# Generated by Django 4.1.6 on 2023-03-05 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0002_photomessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='Fichier_message',
            field=models.FileField(blank=True, upload_to='Message_fichier'),
        ),
        migrations.DeleteModel(
            name='photoMessage',
        ),
    ]
