# Generated by Django 4.1.6 on 2023-03-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Discussion', '0003_chatmessages_fichier_message_delete_photomessage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessages',
            old_name='Fichier_message',
            new_name='fichier_message',
        ),
    ]
