# Generated by Django 4.1.6 on 2023-03-12 09:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0012_panier'),
        ('Discussion', '0005_chatmessages_statut'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessages',
            name='produit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Store.produits'),
        ),
    ]
